Map<int,Map<String,String>>data={
  0:{ 'text':"Always wear mask when your going out",
  'image':'images/wearMask.png'},
  1:{ 'text':"Wash your hands regularly with soap and water,or clean them with alchohol-based hand rub",
    'image':'images/washHand.png'},
  2:{ 'text':"Sanitize your peripherals regularly",
    'image':'images/Sprey.png'},
  3:{ 'text':"Maintain at least 1.5 meter distance between you and people coughing or sneezing",
    'image':'images/maintainDistance.png'},
  4:{ 'text':"Avoid touching your face",
    'image':'images/dontTouchface.png'},
  5:{ 'text':"Cover your mouth and nose when coughing or sneezing",
    'image':'images/coverFace.png'},
  6:{ 'text':"Stay home if you feel unwell",
    'image':'images/StayHome.png'},
};